### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by jvsdr** [FogNo23/DNASrep#1]
There's no wiki and no tutorial! :D

**Comment by FogNo23** [comment]
I thought this would be self explanatory from the files. Mhm, you need a webserver with SSL, I provided an example configuration for Apache2 for details. Obviously you need to adjust IPs and file paths. From the configuration you can also see that you need specific SSL certificates. I put them into /etc/dnas. And last but not least you need the file structure under /var/ww/dnas or whereever you put your www-root for DNAS. PHP must be installed. It definately works with 5, it is said to run with 7, too, but I haven't checked. Keep care of the symbolic links!

If you're running dnsmasq for DNS redirection, there's a configuration file for redirecting the gateways, too. Of course you have to adjust it to your own IPs.

While we're at it: The configuration uses WEAK ciphers for SSL because PS2 is such an old system it cannot handle modern ciphers. I wouldn't use the ciphers/certs for any other service than a DNAS replacement server.
